val1 = input ("Please, enter your first and last name: ")
val2 = input ("Please, enter your position: ")
val3 = int (input ("Please, enter your salary, UAH: "))
val4 = int (input ("Please, enter your age: "))
val1_1 = val1.strip(' ')
val1_s = val1_1.split()
print (f"First name: {val1_s[0].title()}")
print (f"Second name: {val1_s[1].title()}")
print (f"Position: {val2.title()}")
print ("Salary, UAH: %.2f" % (val3))
print ("Age: %d" % (val4))
